// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/providers/liked_tracks_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i13;

import 'package:frontend/models/album.dart' as _i10;
import 'package:frontend/models/artist.dart' as _i11;
import 'package:frontend/models/playlist.dart' as _i3;
import 'package:frontend/models/track.dart' as _i8;
import 'package:frontend/providers/mode_provider.dart' as _i12;
import 'package:frontend/services/api_service.dart' as _i5;
import 'package:frontend/services/offline_storage.dart' as _i9;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sqflite/sqflite.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStreamedResponse_0 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylist_1 extends _i1.SmartFake implements _i3.Playlist {
  _FakePlaylist_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_2 extends _i1.SmartFake implements _i4.Database {
  _FakeDatabase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.StreamedResponse> getAudioStream(String? trackMbid) =>
      (super.noSuchMethod(
            Invocation.method(#getAudioStream, [trackMbid]),
            returnValue: _i6.Future<_i2.StreamedResponse>.value(
              _FakeStreamedResponse_0(
                this,
                Invocation.method(#getAudioStream, [trackMbid]),
              ),
            ),
          )
          as _i6.Future<_i2.StreamedResponse>);

  @override
  _i6.Future<String> getPresignedStreamUrl(String? trackMbid) =>
      (super.noSuchMethod(
            Invocation.method(#getPresignedStreamUrl, [trackMbid]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getPresignedStreamUrl, [trackMbid]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<Map<String, dynamic>> getTaskStatus(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskStatus, [taskId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getPlaylists({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylists, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i3.Playlist> createPlaylist(
    String? name, {
    String? description,
    bool? isPublic = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createPlaylist,
              [name],
              {#description: description, #isPublic: isPublic},
            ),
            returnValue: _i6.Future<_i3.Playlist>.value(
              _FakePlaylist_1(
                this,
                Invocation.method(
                  #createPlaylist,
                  [name],
                  {#description: description, #isPublic: isPublic},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Playlist>);

  @override
  _i6.Future<void> deletePlaylist(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [playlistId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getPlaylistDetail(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistDetail, [playlistId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> addTrackToPlaylist(String? playlistId, String? trackMbid) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackToPlaylist, [playlistId, trackMbid]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getAlbums({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbums, [], {#limit: limit, #offset: offset}),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getAlbum(String? albumMbid) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbum, [albumMbid]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i8.Track>> getAlbumTracks(String? albumMbid) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumTracks, [albumMbid]),
            returnValue: _i6.Future<List<_i8.Track>>.value(<_i8.Track>[]),
          )
          as _i6.Future<List<_i8.Track>>);

  @override
  _i6.Future<Map<String, dynamic>> getArtist(String? artistMbid) =>
      (super.noSuchMethod(
            Invocation.method(#getArtist, [artistMbid]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getArtistAlbums(
    String? artistMbid, {
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getArtistAlbums,
              [artistMbid],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getArtistTracks(
    String? artistMbid, {
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getArtistTracks,
              [artistMbid],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getLikedTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getLikedTracks, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getLikedAlbums() =>
      (super.noSuchMethod(
            Invocation.method(#getLikedAlbums, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getLikedArtists() =>
      (super.noSuchMethod(
            Invocation.method(#getLikedArtists, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<Map<String, dynamic>> likeTrack(String? trackMbid) =>
      (super.noSuchMethod(
            Invocation.method(#likeTrack, [trackMbid]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> unlikeTrack(String? favoriteId) =>
      (super.noSuchMethod(
            Invocation.method(#unlikeTrack, [favoriteId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> likeAlbum(String? albumMbid) =>
      (super.noSuchMethod(
            Invocation.method(#likeAlbum, [albumMbid]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> unlikeAlbumById(String? favoriteId) =>
      (super.noSuchMethod(
            Invocation.method(#unlikeAlbumById, [favoriteId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> likeArtist(String? artistMbid) =>
      (super.noSuchMethod(
            Invocation.method(#likeArtist, [artistMbid]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> unlikeArtist(String? favoriteId) =>
      (super.noSuchMethod(
            Invocation.method(#unlikeArtist, [favoriteId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> search(
    String? query, {
    String? type,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [query],
              {#type: type, #limit: limit, #offset: offset},
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> removeTrackFromPlaylist(
    String? playlistId,
    String? trackMbid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrackFromPlaylist, [
              playlistId,
              trackMbid,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> reorderPlaylistTracks(
    String? playlistId,
    List<Map<String, dynamic>>? newOrder,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderPlaylistTracks, [playlistId, newOrder]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.Playlist> updatePlaylist(
    String? playlistId, {
    String? name,
    String? description,
    bool? isPublic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updatePlaylist,
              [playlistId],
              {#name: name, #description: description, #isPublic: isPublic},
            ),
            returnValue: _i6.Future<_i3.Playlist>.value(
              _FakePlaylist_1(
                this,
                Invocation.method(
                  #updatePlaylist,
                  [playlistId],
                  {#name: name, #description: description, #isPublic: isPublic},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Playlist>);
}

/// A class which mocks [OfflineStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineStorage extends _i1.Mock implements _i9.OfflineStorage {
  MockOfflineStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i4.Database>.value(
              _FakeDatabase_2(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i4.Database>);

  @override
  _i6.Future<void> addDownloadedTrack(_i8.Track? track, String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#addDownloadedTrack, [track, filePath]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeDownloadedTrack(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#removeDownloadedTrack, [trackId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.Track>> getDownloadedTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedTracks, []),
            returnValue: _i6.Future<List<_i8.Track>>.value(<_i8.Track>[]),
          )
          as _i6.Future<List<_i8.Track>>);

  @override
  _i6.Future<Map<String, String>> getDownloadedFilePaths() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedFilePaths, []),
            returnValue: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<bool> isTrackDownloaded(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#isTrackDownloaded, [trackId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> insertPlaylist(_i3.Playlist? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#insertPlaylist, [playlist]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.Playlist>> getAllPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlaylists, []),
            returnValue: _i6.Future<List<_i3.Playlist>>.value(<_i3.Playlist>[]),
          )
          as _i6.Future<List<_i3.Playlist>>);

  @override
  _i6.Future<void> markPlaylistAsDeleted(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markPlaylistAsDeleted, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> permanentlyDeletePlaylist(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDeletePlaylist, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> savePlaylistTracks(
    String? playlistId,
    List<_i8.Track>? tracks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#savePlaylistTracks, [playlistId, tracks]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.Track>> getPlaylistTracks(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistTracks, [playlistId]),
            returnValue: _i6.Future<List<_i8.Track>>.value(<_i8.Track>[]),
          )
          as _i6.Future<List<_i8.Track>>);

  @override
  _i6.Future<void> addLikedTrack(String? favoriteId, _i8.Track? track) =>
      (super.noSuchMethod(
            Invocation.method(#addLikedTrack, [favoriteId, track]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeLikedTrack(String? favoriteId) =>
      (super.noSuchMethod(
            Invocation.method(#removeLikedTrack, [favoriteId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getLikedTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getLikedTracks, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<bool> isTrackLiked(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#isTrackLiked, [trackId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getFavoriteIdForTrack(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteIdForTrack, [trackId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> addLikedAlbum(String? favoriteId, _i10.Album? album) =>
      (super.noSuchMethod(
            Invocation.method(#addLikedAlbum, [favoriteId, album]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeLikedAlbum(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#removeLikedAlbum, [albumId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i10.Album>> getLikedAlbums() =>
      (super.noSuchMethod(
            Invocation.method(#getLikedAlbums, []),
            returnValue: _i6.Future<List<_i10.Album>>.value(<_i10.Album>[]),
          )
          as _i6.Future<List<_i10.Album>>);

  @override
  _i6.Future<String?> getFavoriteIdForAlbum(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteIdForAlbum, [albumId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> addLikedArtist(String? favoriteId, _i11.Artist? artist) =>
      (super.noSuchMethod(
            Invocation.method(#addLikedArtist, [favoriteId, artist]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeLikedArtist(String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#removeLikedArtist, [artistId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.Artist>> getLikedArtists() =>
      (super.noSuchMethod(
            Invocation.method(#getLikedArtists, []),
            returnValue: _i6.Future<List<_i11.Artist>>.value(<_i11.Artist>[]),
          )
          as _i6.Future<List<_i11.Artist>>);

  @override
  _i6.Future<String?> getFavoriteIdForArtist(String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteIdForArtist, [artistId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> addToSyncQueue(
    String? entityType,
    String? action,
    String? entityId, {
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addToSyncQueue,
              [entityType, action, entityId],
              {#payload: payload},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getPendingSyncItems() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncItems, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> removeSyncItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeSyncItem, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveLikedAlbumTracks(
    String? albumId,
    List<_i8.Track>? tracks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveLikedAlbumTracks, [albumId, tracks]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.Track>> getLikedAlbumTracks(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getLikedAlbumTracks, [albumId]),
            returnValue: _i6.Future<List<_i8.Track>>.value(<_i8.Track>[]),
          )
          as _i6.Future<List<_i8.Track>>);

  @override
  _i6.Future<void> removeLikedAlbumTracks(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#removeLikedAlbumTracks, [albumId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isAlbumLiked(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#isAlbumLiked, [albumId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void setDatabaseForTesting(_i4.Database? db) => super.noSuchMethod(
    Invocation.method(#setDatabaseForTesting, [db]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ModeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockModeProvider extends _i1.Mock implements _i12.ModeProvider {
  MockModeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOfflineMode =>
      (super.noSuchMethod(Invocation.getter(#isOfflineMode), returnValue: false)
          as bool);

  @override
  bool get hasInternet =>
      (super.noSuchMethod(Invocation.getter(#hasInternet), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> setOfflineMode(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setOfflineMode, [value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
